### ISSUE TITLE
Would you like to reimplement the experiment results in that paper?

### ISSUE THREAD

**Issue by TianyuanYu** [sagelywizard/snail#1]
I cannot reproduce the results in that paper. Would you like to reproduce the experiments and share them? Thanks very much.

**Comment by sagelywizard** [comment]
I've been able to get close to their performance numbers on their benchmarks, but not quite (some training details were left out of the paper). I'll add the code to reproduce at least their results on Omniglot once I'm able to get their level of performance. I might not include their results on mini-ImageNet, since there are copyright issues around the dataset, which makes it difficult to get access to.
